package view.gui;

import exceptions.InvalidCP;
import exceptions.InvalidName;
import ficheros.ClassFichero;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.validations.UserDataValidations;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author oriolarcroi
 */
public class JframeMain extends javax.swing.JFrame {

    /**
     * Creates new form JframeMain
     *
     * @throws java.io.FileNotFoundException
     */
    public JframeMain() throws FileNotFoundException {
        initComponents();
        initconfig();
        ClassFichero.createFile("C:\\Users\\oriolarcroi\\user_data_OAR.csv");
    }

    private void initconfig() {
        resetForm();
    }

    private void resetForm() {
        cinName.setText("");
        cinNIF.setText("");
        cinDate.setText("");
        cinCP.setText("");
        cinEmail.setText("");
        coutName.setText("");
        coutNIF.setText("");
        coutDate.setText("");
        coutCP.setText("");
        coutEmail.setText("");
        coutAge.setText("");
        cinName.setEditable(true);
        cinNIF.setEditable(true);
        cinDate.setEditable(true);
        cinCP.setEditable(true);
        cinEmail.setEditable(true);
        cinAge.setEditable(false);
        cinAge.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        validador = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        cinName = new javax.swing.JTextField();
        textName = new javax.swing.JLabel();
        coutName = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        textNIF = new javax.swing.JLabel();
        cinNIF = new javax.swing.JTextField();
        coutNIF = new javax.swing.JTextField();
        textEmail = new javax.swing.JLabel();
        cinDate = new javax.swing.JTextField();
        textDate = new javax.swing.JLabel();
        textCP = new javax.swing.JLabel();
        cinEmail = new javax.swing.JTextField();
        btnCLEAR = new javax.swing.JButton();
        btnCSV = new javax.swing.JButton();
        cinCP = new javax.swing.JTextField();
        coutDate = new javax.swing.JTextField();
        coutCP = new javax.swing.JTextField();
        coutEmail = new javax.swing.JTextField();
        cinAge = new javax.swing.JTextField();
        coutAge = new javax.swing.JTextField();
        textEmail1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        validador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        validador.setText("VALIDADOR DATOS USUARIO");

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/media/monlau-fp-es(1).png"))); // NOI18N
        img.setMaximumSize(new java.awt.Dimension(751, 657));
        img.setMinimumSize(new java.awt.Dimension(751, 657));

        cinName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cinName.setText("                 ");
        cinName.setCaretPosition(0);
        cinName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cinName.setDoubleBuffered(true);
        cinName.setMinimumSize(new java.awt.Dimension(135, 19));
        cinName.setName(""); // NOI18N
        cinName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinNameActionPerformed(evt);
            }
        });

        textName.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        textName.setText("Nombre:");

        coutName.setEditable(false);
        coutName.setText("                                   ");
        coutName.setFocusable(false);
        coutName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coutNameActionPerformed(evt);
            }
        });

        btnOK.setBackground(new java.awt.Color(51, 255, 51));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        textNIF.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        textNIF.setText("NIF:");

        cinNIF.setText("                                   ");
        cinNIF.setMinimumSize(new java.awt.Dimension(135, 19));
        cinNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinNIFActionPerformed(evt);
            }
        });

        coutNIF.setEditable(false);
        coutNIF.setText("                                   ");
        coutNIF.setFocusable(false);
        coutNIF.setMinimumSize(new java.awt.Dimension(135, 19));
        coutNIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coutNIFActionPerformed(evt);
            }
        });

        textEmail.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        textEmail.setText("Email:");

        cinDate.setText("                                   ");
        cinDate.setMinimumSize(new java.awt.Dimension(135, 19));
        cinDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinDateActionPerformed(evt);
            }
        });

        textDate.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        textDate.setText("Fecha de Nacimiento: ");

        textCP.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        textCP.setText("Codigo postal:");

        cinEmail.setText("                                   ");
        cinEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinEmailActionPerformed(evt);
            }
        });

        btnCLEAR.setBackground(new java.awt.Color(255, 51, 51));
        btnCLEAR.setText("CLEAR");
        btnCLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLEARActionPerformed(evt);
            }
        });

        btnCSV.setBackground(new java.awt.Color(51, 255, 153));
        btnCSV.setText("CSV");
        btnCSV.setEnabled(false);
        btnCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVActionPerformed(evt);
            }
        });

        cinCP.setText("                                   ");
        cinCP.setMinimumSize(new java.awt.Dimension(135, 19));
        cinCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinCPActionPerformed(evt);
            }
        });

        coutDate.setEditable(false);
        coutDate.setText("                                   ");
        coutDate.setFocusable(false);
        coutDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coutDateActionPerformed(evt);
            }
        });

        coutCP.setEditable(false);
        coutCP.setText("                                   ");
        coutCP.setFocusable(false);
        coutCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coutCPActionPerformed(evt);
            }
        });

        coutEmail.setEditable(false);
        coutEmail.setText("                                   ");
        coutEmail.setFocusable(false);
        coutEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coutEmailActionPerformed(evt);
            }
        });

        cinAge.setEditable(false);
        cinAge.setText("                                   ");
        cinAge.setFocusable(false);
        cinAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinAgeActionPerformed(evt);
            }
        });

        coutAge.setEditable(false);
        coutAge.setText("                                   ");
        coutAge.setFocusable(false);
        coutAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coutAgeActionPerformed(evt);
            }
        });

        textEmail1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        textEmail1.setText("Edad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(validador)
                        .addGap(33, 33, 33)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(btnCLEAR)
                                .addGap(18, 18, 18)
                                .addComponent(btnOK)
                                .addGap(18, 18, 18)
                                .addComponent(btnCSV))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textEmail)
                                    .addComponent(textDate)
                                    .addComponent(textCP)
                                    .addComponent(textEmail1)
                                    .addComponent(textName)
                                    .addComponent(textNIF))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cinAge, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cinName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cinNIF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cinDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cinCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cinEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coutAge, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coutEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(coutNIF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(coutName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(coutCP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(coutDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(validador, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textName)
                            .addComponent(cinName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNIF)
                            .addComponent(cinNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDate)
                            .addComponent(cinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textCP)
                            .addComponent(cinCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textEmail)
                            .addComponent(cinEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textEmail1)
                            .addComponent(cinAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(coutName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coutNIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coutCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coutEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coutAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCSV)
                    .addComponent(btnOK)
                    .addComponent(btnCLEAR))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        btnCSV.setEnabled(false);
        String name = cinName.getText();

//        if (!UserDataValidations.checkName(name)) {
//            coutName.setText("Nombre incorrecto");
//        } else {
//            coutName.setText("Nombre correcto");
//        }
        try {
            UserDataValidations.checkName(name);
            coutName.setText("Nombre correcto");
        } catch (InvalidName ex) {
            coutName.setText(ex.getMessage());
        }

        String id = cinNIF.getText();
        if (!UserDataValidations.checkId(1, id)) {
            coutNIF.setText("NIF incorrecto");
        } else {
            coutNIF.setText("NIF correcto");
        }
        String date = cinDate.getText();
        if (!UserDataValidations.checkFormatDate(date)) {
            coutDate.setText("Fecha incorrecta");
        } else {
            coutDate.setText("Fecha correcta");
            String age = Integer.toString(UserDataValidations.calculateAge(date));
            cinAge.setText(age);
            if (UserDataValidations.calculateAge(date) < 18) {
                coutAge.setText("Eres menos de edad");
            } else {
                coutAge.setText("Eres mayor de edad");
            }
        }
        String zip = cinCP.getText();
//        if (!UserDataValidations.checkPostalCode(zip)) {
//            coutCP.setText("CP incorrecto");
//        } else {
//            coutCP.setText("CP correcto");
//        }

        try {
            UserDataValidations.checkPostalCode(zip);
            coutCP.setText("CP correcto");
        } catch (InvalidCP ex) {
            coutCP.setText(ex.getMessage());
        }

        String email = cinEmail.getText();
        if (!UserDataValidations.checkEmail(email)) {
            coutEmail.setText("Email incorrecto");
        } else {
            coutEmail.setText("Email correcto");
        }

        if (coutName.getText().equals("Nombre correcto")
                && coutNIF.getText().equals("NIF correcto")
                && coutDate.getText().equals("Fecha correcta")
                && coutCP.getText().equals("CP correcto")
                && coutEmail.getText().equals("Email correcto")) {

            btnCSV.setEnabled(true);
        }


    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLEARActionPerformed
        resetForm();    }//GEN-LAST:event_btnCLEARActionPerformed

    private void btnCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVActionPerformed
        String name = cinName.getText();
        String id = cinNIF.getText();
        String date = cinDate.getText();
        String age = cinAge.getText();
        String zip = cinCP.getText();
        String email = cinEmail.getText();
        String line = name + ";" + id + ";" + date + ";" + age + ";" + zip + ";" + email + "\n";
        ClassFichero.writeFile(line);
        JOptionPane.showMessageDialog(this, "Usuario registrado correctamente.", "Registro", JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:
    }//GEN-LAST:event_btnCSVActionPerformed

    private void cinNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinNameActionPerformed

    private void coutNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coutNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coutNIFActionPerformed

    private void coutNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coutNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coutNameActionPerformed

    private void cinNIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinNIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinNIFActionPerformed

    private void cinEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinEmailActionPerformed

    private void coutDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coutDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coutDateActionPerformed

    private void coutCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coutCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coutCPActionPerformed

    private void coutEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coutEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coutEmailActionPerformed

    private void cinDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinDateActionPerformed

    private void cinCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinCPActionPerformed

    private void cinAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinAgeActionPerformed

    private void coutAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coutAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coutAgeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new JframeMain().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(JframeMain.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCLEAR;
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnOK;
    private javax.swing.JTextField cinAge;
    private javax.swing.JTextField cinCP;
    private javax.swing.JTextField cinDate;
    private javax.swing.JTextField cinEmail;
    private javax.swing.JTextField cinNIF;
    private javax.swing.JTextField cinName;
    private javax.swing.JTextField coutAge;
    private javax.swing.JTextField coutCP;
    private javax.swing.JTextField coutDate;
    private javax.swing.JTextField coutEmail;
    private javax.swing.JTextField coutNIF;
    private javax.swing.JTextField coutName;
    private javax.swing.JLabel img;
    private javax.swing.JLabel textCP;
    private javax.swing.JLabel textDate;
    private javax.swing.JLabel textEmail;
    private javax.swing.JLabel textEmail1;
    private javax.swing.JLabel textNIF;
    private javax.swing.JLabel textName;
    private javax.swing.JLabel validador;
    // End of variables declaration//GEN-END:variables

}
